# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.9.5_7.2.1
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
  logstash:
    image: wazuh/wazuh-logstash:3.9.3_6.8.1
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - SECURITY_ENABLED=yes
      - SECURITY_LOGSTASH_USER=service_logstash
      - SECURITY_LOGSTASH_PASS=logstash_pass
      - LOGSTASH_OUTPUT=https://elasticsearch:9200
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SECURITY_CA_PEM=server.TEST-CA-signed.pem
  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.5_7.2.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTICSEARCH_PROTOCOL=http
      - ELASTICSEARCH_IP=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - SECURITY_ENABLED=no
      - SECURITY_ELASTIC_PASSWORD=elastic_pass
      - SECURITY_MAIN_NODE=elasticsearch
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=elasticsearch
      - CLUSTER_NODE_DATA=true
      - CLUSTER_NODE_INGEST=true
      - CLUSTER_MAX_NODES=3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.9.5_7.2.1
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SECURITY_ENABLED=yes
      - SECURITY_KIBANA_USER=service_kibana
      - SECURITY_KIBANA_PASS=kibana_pass
      - SECURITY_KIBANA_SSL_KEY_PATH=/usr/share/kibana/config/ssl/private
      - SECURITY_KIBANA_SSL_CERT_PATH=/usr/share/kibana/config/ssl/certs
      - ELASTICSEARCH_KIBANA_IP=https://elasticsearch:9200
      - SECURITY_CA_PEM=server.TEST-CA-signed.pem
    ports:
      - "5601:5601"
